/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElDatePicker: typeof import('element-plus/es').ElDatePicker
  const ElInp: typeof import('element-plus/es').ElInp
  const ElInput: typeof import('element-plus/es').ElInput
  const ElInputNumber: typeof import('element-plus/es').ElInputNumber
  const ElMessage: typeof import('element-plus/es').ElMessage
  const ElMessageBox: typeof import('element-plus/es').ElMessageBox
  const ElSelect: typeof import('element-plus/es').ElSelect
  const ElSwitch: typeof import('element-plus/es').ElSwitch
}
