/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/global/AsideBar.vue')['default']
    CardHeader: typeof import('./src/components/bases/CardHeader.vue')['default']
    CreateCard: typeof import('./src/components/cards/CreateCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColummn: typeof import('element-plus/es')['ElTableColummn']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableItem: typeof import('element-plus/es')['ElTableItem']
    'ElTableorder:': typeof import('element-plus/es')['ElTableorder:']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterBar: typeof import('./src/components/global/FooterBar.vue')['default']
    GlobalMessage: typeof import('./src/components/global/GlobalMessage.vue')['default']
    Icon: typeof import('./src/components/global/Icon.vue')['default']
    ListCard: typeof import('./src/components/cards/ListCard.vue')['default']
    PageHeader: typeof import('./src/components/bases/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCreateCard: typeof import('./src/components/tags/TagCreateCard.vue')['default']
    TagListCard: typeof import('./src/components/tags/TagListCard.vue')['default']
    TagListTestCard: typeof import('./src/components/tags/TagListTestCard.vue')['default']
    TagSearchCard: typeof import('./src/components/tags/TagSearchCard.vue')['default']
    TopBar: typeof import('./src/components/global/TopBar.vue')['default']
    VButton: typeof import('./src/components/global/VButton.vue')['default']
    VIcon: typeof import('./src/components/global/VIcon.vue')['default']
    VLoading: typeof import('./src/components/global/VLoading.vue')['default']
    VPagination: typeof import('./src/components/global/VPagination.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
