/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/global/AsideBar.vue')['default']
    CardHeader: typeof import('./src/components/bases/CardHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FooterBar: typeof import('./src/components/global/FooterBar.vue')['default']
    GlobalMessage: typeof import('./src/components/global/GlobalMessage.vue')['default']
    Icon: typeof import('./src/components/global/Icon.vue')['default']
    PageHeader: typeof import('./src/components/bases/PageHeader.vue')['default']
    TopBar: typeof import('./src/components/global/TopBar.vue')['default']
    VButton: typeof import('./src/components/global/VButton.vue')['default']
    VIcon: typeof import('./src/components/global/VIcon.vue')['default']
    VLoading: typeof import('./src/components/global/VLoading.vue')['default']
    VPagination: typeof import('./src/components/global/VPagination.vue')['default']
  }
}
